# 第13章 数据分析、科学计算、数据可视化

## 相关标准库和扩展库
用于数据分析、科学计算与可视化的扩展模块主要有:numpy、scipy、pandas、SymPy、matplotlib、Traits、TraitsUI、Chaco、TVTK、Mayavi、VPython、OpenCV。

## 相关标准库和扩展库
• numpy:科学计算包,支持N维数组运算、处理大型矩阵、成熟的广播函数库、矢量运算、线性代数、傅里叶变换、随机数生成,并可与C++/Fortran语言无缝结合。树莓派Python v3默认安装已经包含了numpy。

## 相关标准库和扩展库
• scipy: scipy依赖于numpy,提供了更多的数学工具,包括矩阵运算、线性方程组求解、积分、优化、插值、信号处理、图像处理、统计等等。

## 相关标准库和扩展库
• matplotlib模块依赖于numpy模块和tkinter模块,可以绘制多种形式的图形,包括线图、直方图、饼状图、散点图、误差线图等等,图形质量可满足出版要求,是数据可视化的重要工具。

## 相关标准库和扩展库
• pandas (Python Data Analysis Library)是基于numpy的数据分析模块,提供了大量标准数据模型和高效操作大型数据集所需要的工具,可以说pandas是使得Python能够成为高效且强大的数据分析环境的重要因素之一。

## 相关标准库和扩展库
✓ 大量科学扩展库安装包下载:
http://www.lfd.uci.edu/~gohlke/pythonlibs/
✓ enthought科学计算解决方案:
https://www.enthought.com/
✓ anaconda3下载
https://www.continuum.io/downloads/

## 13.1 numpy简单应用
·导入模块

In [1]:
import numpy as np

## 13.1 numpy简单应用
·生成数组

In [2]:
print(np.array([1, 2, 3, 4, 5])) # 把列表转换为数组
print(np.array((1, 2, 3, 4, 5))) # 把元组转换成数组
print(np.array(range(5))) # 把range对象转换成数组
print(np.array([[1, 2, 3], [4, 5, 6]])) #二维数组
print(np.arange(8)) # 类似于内置函数range()
print(np.arange(1, 10, 2))

[1 2 3 4 5]
[1 2 3 4 5]
[0 1 2 3 4]
[[1 2 3]
 [4 5 6]]
[0 1 2 3 4 5 6 7]
[1 3 5 7 9]


## 13.1 numpy简单应用
·生成数组 (续)

In [3]:
print(np.linspace(0, 10, 11)) #等差数组,包含11个数
print(np.linspace(0, 10, 11, endpoint=False)) #不包含终点
print(np.logspace(0, 100, 10)) # 对数数组
print(np.logspace(1, 6, 5, base=2)) #对数数组,相当于2 ** np.linspace(1,6,5)
print(np.zeros(3)) #全0一维数组
print(np.ones(3)) # 全1一维数组

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.         0.90909091 1.81818182 2.72727273 3.63636364 4.54545455
 5.45454545 6.36363636 7.27272727 8.18181818 9.09090909]
[1.00000000e+000 1.29154967e+011 1.66810054e+022 2.15443469e+033
 2.78255940e+044 3.59381366e+055 4.64158883e+066 5.99484250e+077
 7.74263683e+088 1.00000000e+100]
[ 2.          4.75682846 11.3137085  26.90868529 64.        ]
[0. 0. 0.]
[1. 1. 1.]


## 13.1 numpy简单应用
·生成二维数组

In [4]:
print(np.zeros((3,3))) # 全0二维数组,3行3列
print(np.zeros((3,1))) # 全0二维数组,3行1列
print(np.zeros((1,3))) # 全0二维数组,1行3列
print(np.ones((1,3))) # 全1二维数组
print(np.ones((3,3))) # 全1二维数组

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.]
 [0.]
 [0.]]
[[0. 0. 0.]]
[[1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 13.1 numpy简单应用
·单位矩阵与空数组

In [5]:
print(np.identity(3)) # 单位矩阵
print(np.identity(2))
print(np.empty((3,3))) #空数组,只申请空间而不初始化,元素值是不确定的

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 13.1 numpy简单应用
·随机数组

In [6]:
print(np.random.randint(0, 50, 5)) #随机数组,5个0到50之间的整数
print(np.random.randint(0, 50, (3,5))) #3行5列,15个介于0和50之间的整数
print(np.random.rand(10)) #10个小数
print(np.random.standard_normal(5)) # 从标准正态分布中随机采样

[35 25 41  3 19]
[[34 17 18  8 46]
 [38 24 19  9 14]
 [28 43 43  2 19]]
[0.19457101 0.17443161 0.14481288 0.16329253 0.59222903 0.40909418
 0.84407034 0.3001549  0.83769144 0.14640822]
[-1.24215828 -0.19574477 -1.45328857 -1.24635484  0.80054907]


## 13.1 numpy简单应用
·多维正态分布采样

In [7]:
x = np.random.standard_normal(size=(3,4,2))
print(x)

[[[ 0.09883129 -1.412569  ]
  [ 1.1184718   0.18893275]
  [ 1.8280163  -0.388982  ]
  [-1.09264716  0.84167082]]

 [[-0.52907987  0.06535543]
  [-0.34390055 -0.87527181]
  [ 0.78147497  0.3564339 ]
  [ 0.98040589 -0.6879118 ]]

 [[-1.8891677   0.05053111]
  [ 1.2322129   0.56725019]
  [ 0.87561172 -1.90722286]
  [-0.14528093 -1.00264453]]]


## 13.1 numpy简单应用
·对角矩阵

In [8]:
print(np.diag([1,2,3])) # 对角矩阵
print(np.diag([1,2,3,4])) # 对角矩阵

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## 13.1 numpy简单应用
·测试两个数组是否足够接近

In [9]:
x = np.array([1, 2, 3, 4.001, 5])
y = np.array([1, 1.999, 3, 4.01, 5.1])
print(np.allclose(x, y))
print(np.allclose(x, y, rtol=0.2)) # 设置相对误差参数
print(np.allclose(x, y, atol=0.2)) # 设置绝对误差参数

False
True
True


## 13.1 numpy简单应用
·改变数组元素值

In [10]:
x = np.arange(8)
print(x)
print(np.append(x, 8)) # 返回新数组,增加元素
print(np.append(x, [9,10]))
print(x) #不影响原来的数组
x[3] = 8 #原地修改元素值
print(x)
print(np.insert(x, 1, 8)) # 返回新数组,插入元素

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  9 10]
[0 1 2 3 4 5 6 7]
[0 1 2 8 4 5 6 7]
[0 8 1 2 8 4 5 6 7]


## 13.1 numpy简单应用
·重复元素与修改

In [11]:
print(x.repeat(3)) #元素重复,返回新数组
x.put(0, 9) # 修改指定位置上的元素值
print(x)
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x[0,2] = 4 # 修改第0行第2列的元素值
print(x)

[0 0 0 1 1 1 2 2 2 8 8 8 4 4 4 5 5 5 6 6 6 7 7 7]
[9 1 2 8 4 5 6 7]
[[1 2 4]
 [4 5 6]
 [7 8 9]]


## 13.1 numpy简单应用
•数组与数值的运算

In [12]:
x = np.array((1,2,3,4,5)) # 创建数组对象
print(x)
print(x * 2) # 数组与数值相乘,返回新数组
print(x / 2) # 数组与数值相除
print(x // 2) # 数组与数值整除
print(x ** 3) # 幂运算
print(x + 2) # 数组与数值相加
print(x % 3) # 余数

[1 2 3 4 5]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[  1   8  27  64 125]
[3 4 5 6 7]
[1 2 0 1 2]


## 13.1 numpy简单应用
•数组与数值的运算 (续)

In [13]:
print(2 ** x)
print(2 / x)
print(63 // x)

[ 2  4  8 16 32]
[2.         1.         0.66666667 0.5        0.4       ]
[63 31 21 15 12]


## 13.1 numpy简单应用
·数组与数组的运算

In [14]:
a = np.array((1,2,3))
b = np.array(([1,2,3], [4, 5, 6], [7,8,9]))
c = a * b # 数组与数组相乘
print(c) # a中的每个元素乘以b中的对应列元素
print(c / b) # 数组之间的除法运算
print(c / a)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 13.1 numpy简单应用
·数组与数组的运算 (加减乘除)

In [15]:
print(a + a) # 数组之间的加法运算
print(a * a) # 数组之间的乘法运算
print(a - a) # 数组之间的减法运算
print(a / a) # 数组之间的除法运算

[2 4 6]
[1 4 9]
[0 0 0]
[1. 1. 1.]


## 13.1 numpy简单应用
·转置

In [16]:
b = np.array(([1,2,3], [4,5,6], [7,8,9]))
print(b)
print(b.T) # 转置
a = np.array((1,2,3,4))
print(a)
print(a.T) # 一维数组转置以后和原来是一样的

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4]
[1 2 3 4]


## 13.1 numpy简单应用
•排序

In [17]:
x = np.array([3, 1, 2])
print(np.argsort(x)) # 返回排序后元素的原下标
print(x[np.argsort(x)])
x = np.array([3, 1, 2, 4])
print(np.argsort(x))
print(x[np.argsort(x)]) # 获取排序后的元素
x.sort() # 原地排序
print(x)

[1 2 0]
[1 2 3]
[1 2 0 3]
[1 2 3 4]
[1 2 3 4]


## 13.1 numpy简单应用
·多维数组排序

In [18]:
x = np.array([[0, 3, 4], [2, 2, 1]])
print(np.argsort(x, axis=0)) # 二维数组纵向排序,返回原下标
print(np.argsort(x, axis=1)) # 二维数组横向排序
x.sort(axis=1) #原地排序,横向
print(x) #注意,是每行单独排序
x.sort(axis=0) #原地排序,纵向
print(x) #每列单独排序

[[0 1 1]
 [1 0 0]]
[[0 1 2]
 [2 0 1]]
[[0 3 4]
 [1 2 2]]
[[0 2 2]
 [1 3 4]]


## 13.1 numpy简单应用
点积/内积

In [19]:
a = np.array((5,6,7))
b = np.array((6,6,6))
print(a.dot(b)) # 向量内积
print(np.dot(a,b))
c = np.array(([1,2,3], [4,5,6], [7,8,9])) #二维数组
print(c.dot(a)) # 二维数组的每行与一维向量计算内积
print(a.dot(c)) #一维向量与二维向量的每列计算内积

108
108
[ 38  92 146]
[ 78  96 114]


## 13.1 numpy简单应用
•数组元素访问

In [20]:
b = np.array(([1,2,3], [4,5,6], [7,8,9]))
print(b)
print(b[0]) #第0行
print(b[0][0]) # 第0行第0列的元素值
print(b[0,2]) # 第0行第2列的元素值
print(b[[0,1]]) # 第0行和第1行
print(b[[0,1], [1,2]]) #第0行第1列的元素和第1行第2列的元素

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
1
3
[[1 2 3]
 [4 5 6]]
[2 6]


## 13.1 numpy简单应用
•数组元素访问与修改

In [21]:
x = np.arange(0, 100, 10, dtype=np.floating)
print(x)
print(x[[1, 3, 5]]) #同时访问多个位置上的元素
x[[1, 3, 5]] = 3 #把多个位置上的元素改为相同的值
print(x)
x[[1, 3, 5]] = [34, 45, 56] #把多个位置上的元素改为不同的值
print(x)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
[10. 30. 50.]
[ 0.  3. 20.  3. 40.  3. 60. 70. 80. 90.]
[ 0. 34. 20. 45. 40. 56. 60. 70. 80. 90.]


C:\Users\kun00\AppData\Local\Temp\ipykernel_106456\1918484574.py:1: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  x = np.arange(0, 100, 10, dtype=np.floating)


## 13.1 numpy简单应用
·数组支持函数运算

In [22]:
x = np.arange(0, 100, 10, dtype=np.floating)
print(np.sin(x)) #一维数组中所有元素求正弦值
b = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
print(np.cos(b)) # 二维数组中所有元素求余弦值
print(np.round(np.cos(b))) # 四舍五入

[ 0.         -0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485
 -0.30481062  0.77389068 -0.99388865  0.89399666]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1. -0. -1.]
 [-1.  0.  1.]
 [ 1. -0. -1.]]


C:\Users\kun00\AppData\Local\Temp\ipykernel_106456\604028276.py:1: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  x = np.arange(0, 100, 10, dtype=np.floating)


## 13.1 numpy简单应用
·取整

In [23]:
x = np.random.rand(10) * 10 # 包含10个随机数的数组
print(x)
print(np.floor(x)) # 所有元素向下取整
print(np.ceil(x)) # 所有元素向上取整

[3.59494754 8.5892028  4.72382145 1.85248638 1.70334103 8.02859835
 4.08217891 6.64410953 4.49281885 3.08725361]
[3. 8. 4. 1. 1. 8. 4. 6. 4. 3.]
[4. 9. 5. 2. 2. 9. 5. 7. 5. 4.]


## 13.1 numpy简单应用
·反余弦

In [24]:
x = np.linspace(0, 3.14, 10)
print(x)
y = np.cos(x) #余弦
print(y)
print(np.arccos(y)) # 反余弦

[0.         0.34888889 0.69777778 1.04666667 1.39555556 1.74444444
 2.09333333 2.44222222 2.79111111 3.14      ]
[ 1.          0.93975313  0.76627189  0.50045969  0.17434523 -0.17277674
 -0.4990802  -0.76524761 -0.93920748 -0.99999873]
[0.         0.34888889 0.69777778 1.04666667 1.39555556 1.74444444
 2.09333333 2.44222222 2.79111111 3.14      ]


## 13.1 numpy简单应用
·绝对值与其它数学函数

In [25]:
print(np.absolute(-3)) #绝对值或模
print(np.absolute(3+4j))
print(np.ceil(np.array([1, 2, 3.1]))) #向上取整
print(np.isnan(np.NAN))
print(np.log2(8)) #对数
print(np.log10([100, 1000, 10000]))
print(np.sqrt(range(10))) #平方根

3
5.0
[1. 2. 4.]


AttributeError: module 'numpy' has no attribute 'NAN'

## 13.1 numpy简单应用
•改变数组大小

In [ ]:
a = np.arange(1,11,1)
print(a)
a.shape = 2, 5 # 改为2行5列
print(a)
a.shape = 5, -1 # -1表示自动计算,原地修改
print(a)
b = a.reshape(2,5) # reshape()方法返回新数组
print(b)

## 13.1 numpy简单应用
•切片操作

In [ ]:
a = np.arange(10)
print(a)
print(a[::-1]) # 反向切片
print(a[::2]) #隔一个取一个元素
print(a[:5]) # 前5个元素

## 13.1 numpy简单应用
•多维数组切片

In [ ]:
c = np.arange(25) # 创建数组
c.shape = 5, 5 # 修改数组大小
print(c)
print(c[0, 2:5]) # 第0行中下标[2,5)之间的元素值
print(c[1]) # 第1行所有元素
print(c[2:5, 2:5]) #行下标和列下标都介于[2,5)之间的元素值

## 13.1 numpy简单应用
·布尔运算

In [ ]:
x = np.random.rand(10) #包含10个随机数的数组
print(x)
print(x > 0.5) # 比较数组中每个元素值是否大于0.5
print(x[x > 0.5]) # 获取数组中大于0.5的元素,可用于检测和过滤异常值
print(x < 0.5)
print(np.all(x < 1)) # 测试是否全部元素都小于1

## 13.1 numpy简单应用
·布尔运算 (续)

In [ ]:
print(np.any([1,2,3,4])) #是否存在等价于True的元素
print(np.any([0]))
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
print(a > b) # 两个数组中对应位置上的元素比较
print(a[a>b])
print(a == b)
print(a[a==b])

## 13.1 numpy简单应用
•取整运算

In [ ]:
x = np.random.rand(10) * 50 #10个随机数
print(x)
print(np.int64(x)) #取整
print(np.int32(x))
print(np.int16(x))
print(np.int8(x))

## 13.1 numpy简单应用
·广播

In [ ]:
a = np.arange(0, 60, 10).reshape(-1, 1) #列向量
print(a)
b = np.arange(0, 6) #行向量
print(b)
print(a[0] + b) # 数组与标量的加法
print(a[1] + b)

## 13.1 numpy简单应用
·广播计算

In [ ]:
print(a + b) # 广播
print(a * b)

## 13.1 numpy简单应用
•分段函数

In [ ]:
x = np.random.randint(0, 10, size=(1,10))
print(x)
print(np.where(x < 5, 0, 1)) # 小于5的元素值对应0,其他对应1
print(np.piecewise(x, [x<4, x>7], [lambda x:x*2, lambda x:x*3])) # 小于4的元素乘以2; 大于7的元素乘以3; 其他元素变为0

## 13.1 numpy简单应用
·计算唯一值以及出现次数

In [ ]:
x = np.random.randint(0, 10, 7)
print(x)
counts = np.bincount(x) #元素出现次数,0出现1次, 1、2没出现,3出现1次,以此类推
print(counts)
print(np.sum(counts)) # 所有元素出现次数之和等于数组长度
print(np.unique(x)) # 返回唯一元素值

## 13.1 numpy简单应用
■矩阵运算

In [ ]:
a_list = [3, 5, 7]
a_mat = np.matrix(a_list) # 创建矩阵
print(a_mat)
print(a_mat.T) # 矩阵转置
print(a_mat.shape) # 矩阵形状
print(a_mat.size) # 元素个数

## 13.1 numpy简单应用
■矩阵统计与计算

In [ ]:
print(a_mat.sum()) # 所有元素之和
print(a_mat.max()) #最大值
print(a_mat.mean()) #元素平均值
print(a_mat.max(axis=1)) #横向最大值
print(a_mat.max(axis=0)) # 纵向最大值
b_mat = np.matrix((1, 2, 3)) # 创建矩阵
print(b_mat)
print(a_mat * b_mat.T) # 矩阵相乘

## 13.1 numpy简单应用
■矩阵排序与对角线

In [ ]:
c_mat = np.matrix([[1, 5, 3], [2, 9, 6]]) #创建二维矩阵
print(c_mat)
print(c_mat.argsort(axis=0)) # 纵向排序后的元素序号
print(c_mat.argsort(axis=1)) # 横向排序后的元素序号
d_mat = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(d_mat.diagonal()) # 矩阵对角线元素

## 13.1 numpy简单应用
■特征值与逆矩阵

In [ ]:
print(np.linalg.eig([[1,1],[2,2]])) #特征值与特征向量
x = np.matrix([[1,2], [3,4]])
y = np.linalg.inv(x) # 逆矩阵
print(x * y)
print(y * x)

## 13.1 numpy简单应用
•矩阵QR分解

In [ ]:
a = np.matrix([[1,2,3], [4,5,6]])
print(np.linalg.qr(a))
q, r = np.linalg.qr(a)
print(np.dot(q,r))

## 13.1 numpy简单应用
•矩阵不同维度上的计算

In [ ]:
x = np.matrix(np.arange(0,10).reshape(2,5)) #二维矩阵
print(x)
print(x.sum()) #所有元素之和
print(x.sum(axis=0)) # 纵向求和
print(x.sum(axis=1)) #横向求和
print(x.mean()) #平均值
print(x.mean(axis=1))
print(x.mean(axis=0))

## 13.1 numpy简单应用
•矩阵不同维度上的计算 (续)

In [ ]:
print(x.max()) # 所有元素最大值
print(x.max(axis=0)) # 纵向最大值
print(x.max(axis=1)) # 横向最大值
weight = [0.3, 0.7]
print(np.average(x, axis=0, weights=weight)) #权重

## 13.1 numpy简单应用
•方差与标准差

In [ ]:
x = np.matrix(np.random.randint(0, 10, size=(3,3)))
print(x)
print(x.std()) # 标准差
print(x.std(axis=1)) # 横向标准差
print(x.std(axis=0)) # 纵向标准差
print(x.var(axis=0)) # 纵向方差

## 13.1 numpy简单应用
·读写文件

In [ ]:
x = np.random.rand(4, 10)
np.save('data.npy', x)
y = np.load('data.npy')
print(y)

## 13.1 numpy简单应用
·对象序列化读写

In [ ]:
a_mat = np.matrix([3, 5, 7])
print(a_mat.tostring())
dump_str = a_mat.dumps()
print(dump_str)
print(np.loads(dump_str))
a_mat.dump('x.dat')
print(np.load('x.dat'))

## 13.1 numpy简单应用
・常用常量

In [ ]:
print(np.Inf) #正无穷大
print(np.NAN) # 非数字
print(np.NaN)
print(np.Infinity)
print(np.MAXDIMS)
print(np.NINF) # 负无穷大
print(np.NZERO) #负0

## 13.2 scipy简单应用
• scipy在numpy的基础上增加了大量用于数学计算、科学计算以及工程计算的模块,包括线性代数、常微分方程数值求解、信号处理、图像处理、稀疏矩阵等等。

## 13.2 scipy简单应用
• scipy主要模块有:
* constants: 常数
* special: 特殊函数
* optimize: 数值优化算法,如最小二乘拟合(leastsq)、函数最小值(fmin系列)、非线性方程组求解(fsolve)等等
* interpolate: 插值(interpld、interp2d等等)
* integrate: 数值积分
* signal: 信号处理
* ndimage: 图像处理,包括滤波器模块filters、傅里叶变换模块fourier、图像插值模块interpolation、图像测量模块measurements、形态学图像处理模块morphology等等
* stats: 统计
* misc: 提供了读取图像文件的方法和一些测试图像
* io: 提供了读取Matlab和Fortran文件的方法

## 13.2.1 常数与特殊函数
• scipy的constants模块包含了大量用于科学计算的常数

In [ ]:
from scipy import constants as C
print(C.pi) # 圆周率
print(C.golden) #黄金比例
print(C.c) # 真空中的光速
print(C.h) # 普朗克常数
print(C.mile) #一英里等于多少米
print(C.inch) #一英寸等于多少米
print(C.degree) #一度等于多少弧度
print(C.minute) #一分钟等于多少秒
print(C.g) # 标准重力加速度

## 13.2.1 常数与特殊函数
• scipy的special模块包含了大量函数库,包括基本数学函数、特殊函数以及numpy中的所有函数。

In [ ]:
from scipy import special as S
print(S.cbrt(8)) # 立方根
print(S.exp10(3)) # 10**3
print(S.sindg(90)) # 正弦函数,参数为角度
print(S.round(3.1)) # 四舍五入函数
print(S.round(3.5))
print(S.round(3.499))

## 13.2.2 scipy简单应用
• 特殊数学函数

In [ ]:
print(S.comb(5,3)) #从5个中任选3个的组合数
print(S.perm(5,3)) #排列数
print(S.gamma(4)) # gamma函数
print(S.beta(10, 200)) # beta函数
print(S.sinc(0)) # sinc函数
print(S.sinc(1))

## 13.2.2 scipy简单应用
■ signal模块包含大量滤波函数、B样条插值算法等等。

In [ ]:
import numpy as np
x = np.array([1,2,3])
h = np.array([4,5,6])
import scipy.signal
print(scipy.signal.convolve(x, h)) #一维卷积运算

## 13.2.2 scipy简单应用
二维图像卷积运算。

In [ ]:
import numpy as np
from scipy import signal
from scipy import misc
import matplotlib.pyplot as plt

# face = misc.face(gray=True) # misc.face 现已被移至 scipy.datasets
import scipy.datasets
face = scipy.datasets.face(gray=True)
scharr = np.array([[ -3-3j, 0-10j, +3-3j],
                   [-10+0j, 0+0j, +10+0j],
                   [ -3+3j, 0+10j, +3+3j]]) # Gx + j*Gy
grad = signal.convolve2d(face, scharr, boundary='symm', mode='same')

## 13.2.2 scipy简单应用
二维图像卷积运算绘图

In [ ]:
fig, (ax_orig, ax_mag) = plt.subplots(1, 2, figsize=(10,6))
ax_orig.imshow(face, cmap='gray')
ax_orig.set_title('Original')
ax_orig.set_axis_off()
ax_mag.imshow(np.absolute(grad), cmap='gray')
ax_mag.set_title('Gradient magnitude')
ax_mag.set_axis_off()
fig.show()

## 13.2.2 scipy简单应用
*(展示了浣熊图像及其梯度幅度图的输出)*

## 13.2.2 scipy简单应用
·模块ndimage提供了大量用于N维图像处理的方法
√图像滤波

In [ ]:
from scipy import ndimage
import matplotlib.pyplot as plt
import scipy.datasets
face = scipy.datasets.face() #face是测试图像之一
plt.figure() #创建图形
plt.imshow(face) #绘制测试图像
plt.show() #原始图像

## 13.2.2 scipy简单应用
高斯滤波

In [ ]:
blurred_face = ndimage.gaussian_filter(face, sigma=7) #高斯滤波
plt.imshow(blurred_face)
plt.show() # 显示结果图像

## 13.2.2 scipy简单应用
边缘锐化

In [ ]:
blurred_face1 = ndimage.gaussian_filter(face, sigma=1)
blurred_face3 = ndimage.gaussian_filter(face, sigma=3)
sharp_face = blurred_face3 + 6*(blurred_face3-blurred_face1) #边缘锐化
plt.imshow(sharp_face)
plt.show()

## 13.2.2 scipy简单应用
中值滤波

In [ ]:
median_face = ndimage.median_filter(face, 7) #中值滤波
plt.imshow(median_face)
plt.show()

## 13.2.2 scipy简单应用
√图像测量

In [ ]:
print(ndimage.measurements.maximum(face)) # 最大值
print(ndimage.measurements.maximum_position(face)) #最大值位置
print(ndimage.measurements.extrema(face)) #最小值、最大值及其位置
print(ndimage.measurements.mean(face)) # 平均值
print(ndimage.measurements.median(face)) #中值

## 13.2.2 scipy简单应用
√图像测量 (续)

In [ ]:
print(ndimage.measurements.center_of_mass(face)) #重心
print(ndimage.measurements.sum(face))
print(ndimage.measurements.variance(face)) #方差
print(ndimage.measurements.standard_deviation(face)) # 标准差
# print(ndimage.measurements.histogram(face, 0, 255, 256)) #直方图

## 13.2.2 scipy简单应用(补充)
使用scipy进行多项式计算与符号计算

In [ ]:
from scipy import poly1d
p1 = poly1d([1,2,3,4])
#输出结果中,第一行的数字为第二行对应位置项中x的指数
print(p1)
p2 = poly1d([1,2,3,4], True)
print(p2)

## 13.2.2 scipy简单应用(补充)
使用变量与替换多项式的值

In [ ]:
# 使用z作为变量
p3 = poly1d([1,2,3,4], variable='z')
print(p3)
# 把多项式中的变量替换为指定的值
print(p1(0))
print(p1(1))

## 13.2.2 scipy简单应用(补充)
计算多项式方程的根

In [ ]:
# 计算多项式对应方程的根
print(p1.r)
print(p1(p1.r[0]))

## 13.2.2 scipy简单应用(补充)
查看和修改多项式的系数

In [ ]:
print(p1.c)
p3.c[0] = 5
print(p3)
# 查看多项式最高阶
print(p1.order)

## 13.2.2 scipy简单应用(补充)
查看指定指数对应的项的系数

In [ ]:
#例如,在p1多项式中,指数为3的项的系数为1
print(p1[3])
print(p1[0])

## 13.2.2 scipy简单应用(补充)
加、减、乘、除、幂运算

In [ ]:
print(-p1)
print(p1 + 3)
print(p1 + p2)

## 13.2.2 scipy简单应用(补充)
加、减、乘、除、幂运算 (续)

In [ ]:
print(p1 - 5)
print(p2 - p1)
print(p1 * 3)
print(p1 * p2)
print(p1 * p2 / p2)
print(p2 / p1)

## 13.2.2 scipy简单应用(补充)
多项式的幂运算

In [ ]:
print(p1 ** 2)
print(p1 * p1)

## 13.2.2 scipy简单应用(补充)
导数

In [ ]:
#一阶导数
print(p1.deriv())
# 二阶导数
print(p1.deriv(2))

## 13.2.2 scipy简单应用(补充)
多项式的不定积分

In [ ]:
#一重不定积分,设常数项为0
print(p1.integ(m=1, k=0))
#二重不定积分,设常数项为3
print(p1.integ(m=2, k=3))

## 13.2.2 scipy积分
$I=\int_{0}^{4.5}J_{2.5}(x)dx.$

In [ ]:
import scipy.integrate as integrate
import scipy.special as special
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
print(result)

## 13.2.2 scipy多重积分
$I=\int_{y=0}^{1/2}\int_{x=0}^{1-2y}xy~dx~dy=\frac{1}{96}.$

In [ ]:
from scipy import integrate
def f(x, y):
    return x*y
def bounds_y():
    return [0, 0.5]
def bounds_x(y):
    return [0, 1-2*y]
print(integrate.nquad(f, [bounds_x, bounds_y]))

## 13.2.2 scipy插值
一维插值

In [ ]:
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt
x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(-x**2/9.0)
f = interp1d(x, y)
f2 = interp1d(x, y, kind='cubic')
xnew = np.linspace(0, 10, num=41, endpoint=True)
plt.plot(x, y, 'o', xnew, f(xnew), '-', xnew, f2(xnew), '--')
plt.legend(['data', 'linear', 'cubic'], loc='best')
plt.show()

## 13.2.2 scipy多维插值
网格数据插值

In [ ]:
def func(x, y):
    return x*(1-x)*np.cos(4*np.pi*x) * np.sin(4*np.pi*y**2)**2
grid_x, grid_y = np.mgrid[0:1:100j, 0:1:200j]
points = np.random.rand(1000, 2)
values = func(points[:,0], points[:,1])
from scipy.interpolate import griddata
grid_z0 = griddata(points, values, (grid_x, grid_y), method='nearest')
grid_z1 = griddata(points, values, (grid_x, grid_y), method='linear')
grid_z2 = griddata(points, values, (grid_x, grid_y), method='cubic')

## 13.2.2 scipy优化
最优化函数 (Rosenbrock)

In [ ]:
import numpy as np
from scipy.optimize import minimize
def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='nelder-mead', options={'xatol': 1e-8, 'disp': True})
print(res.x)

## 13.2.2 scipy全局优化
Eggholder 函数 3D 可视化

In [ ]:
def eggholder(x):
    return (-(x[1]+47)*np.sin(np.sqrt(abs(x[0]/2+(x[1]+47)))) - x[0]*np.sin(np.sqrt(abs(x[0]-(x[1]+47)))))
bounds = [(-512, 512), (-512, 512)]
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
x = np.arange(-512, 513)
y = np.arange(-512, 513)
xgrid, ygrid = np.meshgrid(x, y)
xy = np.stack([xgrid, ygrid])
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.view_init(45, -45)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('eggholder(x, y)')
ax.plot_surface(xgrid, ygrid, eggholder(xy), cmap='terrain')
plt.show()

## 13.2.2 scipy全局优化
不同优化算法测试

In [ ]:
from scipy import optimize
results = dict()
results['DA'] = optimize.dual_annealing(eggholder, bounds)
print(results['DA'])
results['DE'] = optimize.differential_evolution(eggholder, bounds)
results['BH'] = optimize.basinhopping(eggholder, bounds)

## 13.2.2 scipy全局优化
优化结果 2D 可视化标记

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)
im = ax.imshow(eggholder(xy), interpolation='bilinear', origin='lower', cmap='gray')
ax.set_xlabel('x')
ax.set_ylabel('y')
def plot_point(res, marker='o', color=None):
    ax.plot(512+res.x[0], 512+res.x[1], marker=marker, color=color, ms=10)
plot_point(results['BH'], color='y')
plot_point(results['DE'], color='c')
plot_point(results['DA'], color='w')
ax.set_xlim([-4, 514*2])
ax.set_ylim([-4, 514*2])
plt.show()

## 13.2.3 sklearn分类
此页面展示了不同分类算法(Nearest Neighbors, Linear SVM, RBF SVM, Gaussian Process, Decision Tree, Random Forest, Neural Net, AdaBoost, Naive Bayes, QDA)在多组数据(Input data)上的分类边界效果对比图。

## 13.2.3 sklearn聚类
此页面展示了不同聚类算法(MiniBatchKMeans, AffinityPropagation, MeanShift, SpectralClustering, Ward AgglomerativeClustering, DBSCAN, OPTICS, Birch, GaussianMixture)在多种分布数据集上的聚类效果与运算时间对比图。